// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mars/create_pub_events.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreatePubEvents struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PubId        string `protobuf:"bytes,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Question     string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answers      string `protobuf:"bytes,4,opt,name=answers,proto3" json:"answers,omitempty"`
	PremAmount   string `protobuf:"bytes,5,opt,name=premAmount,proto3" json:"premAmount,omitempty"`
	StartTime    string `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime      string `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ExpertAmount string `protobuf:"bytes,8,opt,name=expertAmount,proto3" json:"expertAmount,omitempty"`
	Creator      string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *CreatePubEvents) Reset()         { *m = CreatePubEvents{} }
func (m *CreatePubEvents) String() string { return proto.CompactTextString(m) }
func (*CreatePubEvents) ProtoMessage()    {}
func (*CreatePubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5234c800d810187, []int{0}
}
func (m *CreatePubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePubEvents.Merge(m, src)
}
func (m *CreatePubEvents) XXX_Size() int {
	return m.Size()
}
func (m *CreatePubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePubEvents proto.InternalMessageInfo

func (m *CreatePubEvents) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePubEvents) GetPubId() string {
	if m != nil {
		return m.PubId
	}
	return ""
}

func (m *CreatePubEvents) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *CreatePubEvents) GetAnswers() string {
	if m != nil {
		return m.Answers
	}
	return ""
}

func (m *CreatePubEvents) GetPremAmount() string {
	if m != nil {
		return m.PremAmount
	}
	return ""
}

func (m *CreatePubEvents) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreatePubEvents) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CreatePubEvents) GetExpertAmount() string {
	if m != nil {
		return m.ExpertAmount
	}
	return ""
}

func (m *CreatePubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePubEvents)(nil), "VoroshilovMax.mars.mars.CreatePubEvents")
}

func init() { proto.RegisterFile("mars/create_pub_events.proto", fileDescriptor_d5234c800d810187) }

var fileDescriptor_d5234c800d810187 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xeb, 0xd0, 0xab, 0x85, 0x40, 0xb2, 0x2a, 0x61, 0x55, 0x95, 0x55, 0x75, 0xaa, 0x18,
	0x9a, 0x81, 0x27, 0xe0, 0x36, 0x30, 0x20, 0xa1, 0x0a, 0x31, 0xb0, 0x54, 0x49, 0x73, 0x94, 0x5a,
	0x22, 0xb1, 0xf1, 0xa5, 0x94, 0x99, 0x17, 0xe0, 0xb1, 0x18, 0x3b, 0x32, 0xa2, 0xe4, 0x45, 0x50,
	0x4e, 0xc2, 0xa5, 0x8b, 0xed, 0xff, 0x7c, 0xff, 0xf9, 0x87, 0xdf, 0x74, 0x9c, 0x45, 0xc6, 0x86,
	0x2b, 0x03, 0x91, 0x83, 0xa5, 0xf6, 0xf1, 0x12, 0x36, 0x90, 0x3b, 0x3b, 0xd7, 0x46, 0x39, 0xc5,
	0x4e, 0x1e, 0x94, 0x51, 0x76, 0x2d, 0x9f, 0xd4, 0xe6, 0x36, 0xda, 0xce, 0x2b, 0x2f, 0x1e, 0xa3,
	0x61, 0xaa, 0x52, 0x85, 0x9e, 0xb0, 0x7a, 0xd5, 0xf6, 0xe9, 0x5b, 0x40, 0x8f, 0x2f, 0x31, 0xea,
	0xce, 0xc7, 0xd7, 0x18, 0xc4, 0x8e, 0x68, 0x20, 0x13, 0x4e, 0x26, 0x64, 0xd6, 0x5e, 0x04, 0x32,
	0x61, 0x43, 0xda, 0xd1, 0x3e, 0xbe, 0x49, 0x78, 0x30, 0x21, 0xb3, 0xc1, 0xa2, 0x16, 0x6c, 0x44,
	0xfb, 0xcf, 0x1e, 0xac, 0x93, 0x2a, 0xe7, 0x07, 0x08, 0x7e, 0x35, 0xe3, 0xb4, 0x17, 0xe5, 0xf6,
	0x05, 0x8c, 0xe5, 0x6d, 0x44, 0x3f, 0x92, 0x09, 0x4a, 0xb5, 0x81, 0xec, 0x3c, 0x53, 0x3e, 0x77,
	0xbc, 0x83, 0xf0, 0xdf, 0x84, 0x8d, 0xe9, 0xc0, 0xba, 0xc8, 0xb8, 0x7b, 0x99, 0x01, 0xef, 0x22,
	0xfe, 0x1b, 0x54, 0xb9, 0x90, 0x27, 0xc8, 0x7a, 0x75, 0x6e, 0x23, 0xd9, 0x94, 0x1e, 0xc2, 0x56,
	0x83, 0x71, 0x4d, 0x72, 0x1f, 0xf1, 0xde, 0xac, 0xda, 0xc6, 0xd6, 0x94, 0xe1, 0x83, 0x7a, 0xbb,
	0x91, 0x17, 0x57, 0x1f, 0x85, 0x20, 0xbb, 0x42, 0x90, 0xaf, 0x42, 0x90, 0xf7, 0x52, 0xb4, 0x76,
	0xa5, 0x68, 0x7d, 0x96, 0xa2, 0xf5, 0x78, 0x9a, 0x4a, 0xb7, 0xf6, 0xf1, 0x7c, 0xa5, 0xb2, 0x70,
	0xaf, 0xd9, 0x10, 0x7f, 0xa1, 0xb9, 0xdc, 0xab, 0x06, 0x1b, 0x77, 0xb1, 0xd2, 0xb3, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0x9b, 0xee, 0xd9, 0xa1, 0x01, 0x00, 0x00,
}

func (m *CreatePubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ExpertAmount) > 0 {
		i -= len(m.ExpertAmount)
		copy(dAtA[i:], m.ExpertAmount)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.ExpertAmount)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.EndTime) > 0 {
		i -= len(m.EndTime)
		copy(dAtA[i:], m.EndTime)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.EndTime)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.StartTime) > 0 {
		i -= len(m.StartTime)
		copy(dAtA[i:], m.StartTime)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.StartTime)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PremAmount) > 0 {
		i -= len(m.PremAmount)
		copy(dAtA[i:], m.PremAmount)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.PremAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Answers) > 0 {
		i -= len(m.Answers)
		copy(dAtA[i:], m.Answers)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.Answers)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Question) > 0 {
		i -= len(m.Question)
		copy(dAtA[i:], m.Question)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.Question)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PubId) > 0 {
		i -= len(m.PubId)
		copy(dAtA[i:], m.PubId)
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(len(m.PubId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCreatePubEvents(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCreatePubEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovCreatePubEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreatePubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCreatePubEvents(uint64(m.Id))
	}
	l = len(m.PubId)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.Question)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.Answers)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.PremAmount)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.StartTime)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.EndTime)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.ExpertAmount)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCreatePubEvents(uint64(l))
	}
	return n
}

func sovCreatePubEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCreatePubEvents(x uint64) (n int) {
	return sovCreatePubEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreatePubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCreatePubEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Question", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Question = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PremAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PremAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpertAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpertAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCreatePubEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCreatePubEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCreatePubEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCreatePubEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCreatePubEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCreatePubEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCreatePubEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCreatePubEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCreatePubEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCreatePubEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCreatePubEvents = fmt.Errorf("proto: unexpected end of group")
)
