// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mars/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetCreatePrivEventsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCreatePrivEventsRequest) Reset()         { *m = QueryGetCreatePrivEventsRequest{} }
func (m *QueryGetCreatePrivEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePrivEventsRequest) ProtoMessage()    {}
func (*QueryGetCreatePrivEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{0}
}
func (m *QueryGetCreatePrivEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePrivEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePrivEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePrivEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePrivEventsRequest.Merge(m, src)
}
func (m *QueryGetCreatePrivEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePrivEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePrivEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePrivEventsRequest proto.InternalMessageInfo

func (m *QueryGetCreatePrivEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCreatePrivEventsResponse struct {
	CreatePrivEvents CreatePrivEvents `protobuf:"bytes,1,opt,name=CreatePrivEvents,proto3" json:"CreatePrivEvents"`
}

func (m *QueryGetCreatePrivEventsResponse) Reset()         { *m = QueryGetCreatePrivEventsResponse{} }
func (m *QueryGetCreatePrivEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePrivEventsResponse) ProtoMessage()    {}
func (*QueryGetCreatePrivEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{1}
}
func (m *QueryGetCreatePrivEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePrivEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePrivEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePrivEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePrivEventsResponse.Merge(m, src)
}
func (m *QueryGetCreatePrivEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePrivEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePrivEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePrivEventsResponse proto.InternalMessageInfo

func (m *QueryGetCreatePrivEventsResponse) GetCreatePrivEvents() CreatePrivEvents {
	if m != nil {
		return m.CreatePrivEvents
	}
	return CreatePrivEvents{}
}

type QueryAllCreatePrivEventsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePrivEventsRequest) Reset()         { *m = QueryAllCreatePrivEventsRequest{} }
func (m *QueryAllCreatePrivEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePrivEventsRequest) ProtoMessage()    {}
func (*QueryAllCreatePrivEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{2}
}
func (m *QueryAllCreatePrivEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePrivEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePrivEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePrivEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePrivEventsRequest.Merge(m, src)
}
func (m *QueryAllCreatePrivEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePrivEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePrivEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePrivEventsRequest proto.InternalMessageInfo

func (m *QueryAllCreatePrivEventsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCreatePrivEventsResponse struct {
	CreatePrivEvents []CreatePrivEvents  `protobuf:"bytes,1,rep,name=CreatePrivEvents,proto3" json:"CreatePrivEvents"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePrivEventsResponse) Reset()         { *m = QueryAllCreatePrivEventsResponse{} }
func (m *QueryAllCreatePrivEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePrivEventsResponse) ProtoMessage()    {}
func (*QueryAllCreatePrivEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{3}
}
func (m *QueryAllCreatePrivEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePrivEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePrivEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePrivEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePrivEventsResponse.Merge(m, src)
}
func (m *QueryAllCreatePrivEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePrivEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePrivEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePrivEventsResponse proto.InternalMessageInfo

func (m *QueryAllCreatePrivEventsResponse) GetCreatePrivEvents() []CreatePrivEvents {
	if m != nil {
		return m.CreatePrivEvents
	}
	return nil
}

func (m *QueryAllCreatePrivEventsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCreatePubEventsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCreatePubEventsRequest) Reset()         { *m = QueryGetCreatePubEventsRequest{} }
func (m *QueryGetCreatePubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePubEventsRequest) ProtoMessage()    {}
func (*QueryGetCreatePubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{4}
}
func (m *QueryGetCreatePubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePubEventsRequest.Merge(m, src)
}
func (m *QueryGetCreatePubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePubEventsRequest proto.InternalMessageInfo

func (m *QueryGetCreatePubEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCreatePubEventsResponse struct {
	CreatePubEvents CreatePubEvents `protobuf:"bytes,1,opt,name=CreatePubEvents,proto3" json:"CreatePubEvents"`
}

func (m *QueryGetCreatePubEventsResponse) Reset()         { *m = QueryGetCreatePubEventsResponse{} }
func (m *QueryGetCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePubEventsResponse) ProtoMessage()    {}
func (*QueryGetCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{5}
}
func (m *QueryGetCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePubEventsResponse.Merge(m, src)
}
func (m *QueryGetCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePubEventsResponse proto.InternalMessageInfo

func (m *QueryGetCreatePubEventsResponse) GetCreatePubEvents() CreatePubEvents {
	if m != nil {
		return m.CreatePubEvents
	}
	return CreatePubEvents{}
}

type QueryAllCreatePubEventsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePubEventsRequest) Reset()         { *m = QueryAllCreatePubEventsRequest{} }
func (m *QueryAllCreatePubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePubEventsRequest) ProtoMessage()    {}
func (*QueryAllCreatePubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{6}
}
func (m *QueryAllCreatePubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePubEventsRequest.Merge(m, src)
}
func (m *QueryAllCreatePubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePubEventsRequest proto.InternalMessageInfo

func (m *QueryAllCreatePubEventsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCreatePubEventsResponse struct {
	CreatePubEvents []CreatePubEvents   `protobuf:"bytes,1,rep,name=CreatePubEvents,proto3" json:"CreatePubEvents"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePubEventsResponse) Reset()         { *m = QueryAllCreatePubEventsResponse{} }
func (m *QueryAllCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePubEventsResponse) ProtoMessage()    {}
func (*QueryAllCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b7a2d68082a6ac8, []int{7}
}
func (m *QueryAllCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePubEventsResponse.Merge(m, src)
}
func (m *QueryAllCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePubEventsResponse proto.InternalMessageInfo

func (m *QueryAllCreatePubEventsResponse) GetCreatePubEvents() []CreatePubEvents {
	if m != nil {
		return m.CreatePubEvents
	}
	return nil
}

func (m *QueryAllCreatePubEventsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetCreatePrivEventsRequest)(nil), "VoroshilovMax.mars.mars.QueryGetCreatePrivEventsRequest")
	proto.RegisterType((*QueryGetCreatePrivEventsResponse)(nil), "VoroshilovMax.mars.mars.QueryGetCreatePrivEventsResponse")
	proto.RegisterType((*QueryAllCreatePrivEventsRequest)(nil), "VoroshilovMax.mars.mars.QueryAllCreatePrivEventsRequest")
	proto.RegisterType((*QueryAllCreatePrivEventsResponse)(nil), "VoroshilovMax.mars.mars.QueryAllCreatePrivEventsResponse")
	proto.RegisterType((*QueryGetCreatePubEventsRequest)(nil), "VoroshilovMax.mars.mars.QueryGetCreatePubEventsRequest")
	proto.RegisterType((*QueryGetCreatePubEventsResponse)(nil), "VoroshilovMax.mars.mars.QueryGetCreatePubEventsResponse")
	proto.RegisterType((*QueryAllCreatePubEventsRequest)(nil), "VoroshilovMax.mars.mars.QueryAllCreatePubEventsRequest")
	proto.RegisterType((*QueryAllCreatePubEventsResponse)(nil), "VoroshilovMax.mars.mars.QueryAllCreatePubEventsResponse")
}

func init() { proto.RegisterFile("mars/query.proto", fileDescriptor_2b7a2d68082a6ac8) }

var fileDescriptor_2b7a2d68082a6ac8 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0x69, 0xed, 0x61, 0x04, 0x2d, 0xa3, 0xa0, 0x84, 0xba, 0x2d, 0x7b, 0xd0, 0x34,
	0xe2, 0x4c, 0x52, 0xd1, 0xd6, 0x63, 0xeb, 0x9f, 0x9e, 0x84, 0x9a, 0x83, 0x88, 0x1e, 0xca, 0x6c,
	0x32, 0x6c, 0x06, 0x36, 0x3b, 0xdb, 0x9d, 0x49, 0xb0, 0x14, 0x11, 0xf4, 0x0b, 0x08, 0x7e, 0x1a,
	0x11, 0xf1, 0xe2, 0x21, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0x89, 0x1f, 0x44, 0x76, 0x76, 0x42, 0xba,
	0xbb, 0xdd, 0xec, 0x56, 0x72, 0x49, 0x96, 0xcc, 0x3e, 0xef, 0x3c, 0xbf, 0xe7, 0x7d, 0x67, 0x02,
	0x57, 0xfb, 0x34, 0x94, 0xe4, 0x68, 0xc0, 0xc2, 0x63, 0x1c, 0x84, 0x42, 0x09, 0x74, 0xe3, 0xa5,
	0x08, 0x85, 0xec, 0x71, 0x4f, 0x0c, 0x9f, 0xd3, 0xb7, 0x38, 0x5a, 0xd7, 0x1f, 0xb5, 0x35, 0x57,
	0x08, 0xd7, 0x63, 0x84, 0x06, 0x9c, 0x50, 0xdf, 0x17, 0x8a, 0x2a, 0x2e, 0x7c, 0x19, 0xcb, 0x6a,
	0x8d, 0x8e, 0x90, 0x7d, 0x21, 0x89, 0x43, 0x25, 0x8b, 0xeb, 0x91, 0x61, 0xcb, 0x61, 0x8a, 0xb6,
	0x48, 0x40, 0x5d, 0xee, 0xeb, 0x97, 0xcd, 0xbb, 0xb7, 0xf4, 0xa6, 0x9d, 0x90, 0x51, 0xc5, 0x0e,
	0x83, 0x90, 0x0f, 0x0f, 0xd9, 0x90, 0xf9, 0x6a, 0x5a, 0x6a, 0x2d, 0xb1, 0x3c, 0x70, 0x92, 0xab,
	0xd7, 0x5d, 0xe1, 0x0a, 0xfd, 0x48, 0xa2, 0xa7, 0xf8, 0x57, 0xbb, 0x05, 0xd7, 0x5f, 0x44, 0x9b,
	0xee, 0x33, 0xf5, 0x58, 0x0b, 0x0f, 0x42, 0x3e, 0x7c, 0xaa, 0x75, 0x6d, 0x76, 0x34, 0x60, 0x52,
	0xa1, 0x2b, 0xb0, 0xca, 0xbb, 0x37, 0xc1, 0x06, 0xa8, 0x2f, 0xb7, 0xab, 0xbc, 0x6b, 0xbf, 0x87,
	0x1b, 0xf9, 0x12, 0x19, 0x08, 0x5f, 0x32, 0xf4, 0x06, 0xae, 0xa6, 0xd7, 0x74, 0x85, 0xcb, 0x5b,
	0x9b, 0x38, 0x27, 0x27, 0x9c, 0x16, 0xec, 0x2d, 0x8f, 0x7e, 0xaf, 0x57, 0xda, 0x99, 0x42, 0x36,
	0x37, 0x9e, 0x77, 0x3d, 0x2f, 0xcf, 0xf3, 0x33, 0x08, 0x67, 0xe9, 0x99, 0x9d, 0x6f, 0xe3, 0x38,
	0x6a, 0x1c, 0x45, 0x8d, 0xe3, 0xd6, 0x99, 0xa8, 0xf1, 0x01, 0x75, 0x99, 0xd1, 0xb6, 0xcf, 0x28,
	0xed, 0x11, 0x30, 0xb0, 0xe7, 0xee, 0x35, 0x17, 0x76, 0x69, 0x21, 0xb0, 0x68, 0x3f, 0x41, 0x52,
	0xd5, 0x24, 0x77, 0x0a, 0x49, 0x62, 0x67, 0x09, 0x94, 0x26, 0xb4, 0x52, 0x6d, 0x1b, 0x38, 0xf3,
	0x1b, 0x7d, 0x92, 0x99, 0x8d, 0x99, 0xc2, 0xa0, 0xbf, 0x82, 0x57, 0x53, 0x4b, 0x26, 0xec, 0x7a,
	0x11, 0xf9, 0xf4, 0x7d, 0x03, 0x9e, 0x2e, 0x63, 0xf7, 0x8c, 0xdd, 0x59, 0xf0, 0x69, 0xbb, 0x8b,
	0xea, 0xf1, 0x0f, 0x90, 0x99, 0xa7, 0x72, 0x9c, 0x4b, 0x0b, 0xe0, 0x5c, 0x58, 0x7f, 0xb7, 0x3e,
	0xae, 0xc0, 0x4b, 0x1a, 0x03, 0x7d, 0x07, 0xd9, 0x81, 0x44, 0x3b, 0xb9, 0x46, 0x0b, 0xce, 0x7f,
	0xed, 0xd1, 0x7f, 0x28, 0x63, 0x7f, 0xf6, 0xc3, 0x0f, 0x3f, 0xff, 0x7e, 0xae, 0x36, 0x11, 0x26,
	0x89, 0x12, 0x44, 0x5f, 0x54, 0x67, 0x6e, 0xab, 0x99, 0x94, 0x9c, 0xf0, 0xee, 0x3b, 0xf4, 0x0d,
	0xc0, 0x6b, 0xe9, 0xa2, 0xbb, 0x9e, 0x57, 0x04, 0x91, 0x7f, 0x21, 0x14, 0x41, 0xcc, 0x39, 0xde,
	0x76, 0x4b, 0x43, 0xdc, 0x45, 0x9b, 0xa5, 0x21, 0xd0, 0x57, 0x90, 0x99, 0x17, 0xb4, 0x5d, 0x36,
	0xc6, 0xd4, 0x9c, 0xd7, 0x76, 0x2e, 0x2e, 0x34, 0xce, 0x1f, 0x68, 0xe7, 0x04, 0xdd, 0x2b, 0x72,
	0x3e, 0x55, 0xc6, 0xe9, 0x7f, 0x01, 0x10, 0xa5, 0x4a, 0x46, 0xe1, 0x6f, 0x97, 0x8d, 0xf0, 0x82,
	0x00, 0xf9, 0xc7, 0xce, 0x6e, 0x6a, 0x80, 0x06, 0xaa, 0x97, 0x05, 0xd8, 0x7b, 0x32, 0x1a, 0x5b,
	0xe0, 0x74, 0x6c, 0x81, 0x3f, 0x63, 0x0b, 0x7c, 0x9a, 0x58, 0x95, 0xd3, 0x89, 0x55, 0xf9, 0x35,
	0xb1, 0x2a, 0xaf, 0x1b, 0x2e, 0x57, 0xbd, 0x81, 0x83, 0x3b, 0xa2, 0x7f, 0x5e, 0x35, 0xf3, 0xa5,
	0x8e, 0x03, 0x26, 0x9d, 0x15, 0xfd, 0xe7, 0x78, 0xff, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4,
	0x00, 0x9f, 0x63, 0xe6, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a createPrivEvents by id.
	CreatePrivEvents(ctx context.Context, in *QueryGetCreatePrivEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePrivEventsResponse, error)
	// Queries a list of createPrivEvents items.
	CreatePrivEventsAll(ctx context.Context, in *QueryAllCreatePrivEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePrivEventsResponse, error)
	// Queries a createPubEvents by id.
	CreatePubEvents(ctx context.Context, in *QueryGetCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePubEventsResponse, error)
	// Queries a list of createPubEvents items.
	CreatePubEventsAll(ctx context.Context, in *QueryAllCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePubEventsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CreatePrivEvents(ctx context.Context, in *QueryGetCreatePrivEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePrivEventsResponse, error) {
	out := new(QueryGetCreatePrivEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.mars.mars.Query/CreatePrivEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CreatePrivEventsAll(ctx context.Context, in *QueryAllCreatePrivEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePrivEventsResponse, error) {
	out := new(QueryAllCreatePrivEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.mars.mars.Query/CreatePrivEventsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CreatePubEvents(ctx context.Context, in *QueryGetCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePubEventsResponse, error) {
	out := new(QueryGetCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.mars.mars.Query/CreatePubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CreatePubEventsAll(ctx context.Context, in *QueryAllCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePubEventsResponse, error) {
	out := new(QueryAllCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.mars.mars.Query/CreatePubEventsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a createPrivEvents by id.
	CreatePrivEvents(context.Context, *QueryGetCreatePrivEventsRequest) (*QueryGetCreatePrivEventsResponse, error)
	// Queries a list of createPrivEvents items.
	CreatePrivEventsAll(context.Context, *QueryAllCreatePrivEventsRequest) (*QueryAllCreatePrivEventsResponse, error)
	// Queries a createPubEvents by id.
	CreatePubEvents(context.Context, *QueryGetCreatePubEventsRequest) (*QueryGetCreatePubEventsResponse, error)
	// Queries a list of createPubEvents items.
	CreatePubEventsAll(context.Context, *QueryAllCreatePubEventsRequest) (*QueryAllCreatePubEventsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CreatePrivEvents(ctx context.Context, req *QueryGetCreatePrivEventsRequest) (*QueryGetCreatePrivEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrivEvents not implemented")
}
func (*UnimplementedQueryServer) CreatePrivEventsAll(ctx context.Context, req *QueryAllCreatePrivEventsRequest) (*QueryAllCreatePrivEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrivEventsAll not implemented")
}
func (*UnimplementedQueryServer) CreatePubEvents(ctx context.Context, req *QueryGetCreatePubEventsRequest) (*QueryGetCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePubEvents not implemented")
}
func (*UnimplementedQueryServer) CreatePubEventsAll(ctx context.Context, req *QueryAllCreatePubEventsRequest) (*QueryAllCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePubEventsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CreatePrivEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCreatePrivEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePrivEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.mars.mars.Query/CreatePrivEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePrivEvents(ctx, req.(*QueryGetCreatePrivEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CreatePrivEventsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCreatePrivEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePrivEventsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.mars.mars.Query/CreatePrivEventsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePrivEventsAll(ctx, req.(*QueryAllCreatePrivEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CreatePubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCreatePubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.mars.mars.Query/CreatePubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePubEvents(ctx, req.(*QueryGetCreatePubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CreatePubEventsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCreatePubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePubEventsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.mars.mars.Query/CreatePubEventsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePubEventsAll(ctx, req.(*QueryAllCreatePubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VoroshilovMax.mars.mars.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrivEvents",
			Handler:    _Query_CreatePrivEvents_Handler,
		},
		{
			MethodName: "CreatePrivEventsAll",
			Handler:    _Query_CreatePrivEventsAll_Handler,
		},
		{
			MethodName: "CreatePubEvents",
			Handler:    _Query_CreatePubEvents_Handler,
		},
		{
			MethodName: "CreatePubEventsAll",
			Handler:    _Query_CreatePubEventsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mars/query.proto",
}

func (m *QueryGetCreatePrivEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePrivEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePrivEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatePrivEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePrivEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePrivEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CreatePrivEvents.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePrivEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePrivEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePrivEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePrivEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePrivEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePrivEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CreatePrivEvents) > 0 {
		for iNdEx := len(m.CreatePrivEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatePrivEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatePubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CreatePubEvents.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CreatePubEvents) > 0 {
		for iNdEx := len(m.CreatePubEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatePubEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetCreatePrivEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCreatePrivEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CreatePrivEvents.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCreatePrivEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatePrivEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CreatePrivEvents) > 0 {
		for _, e := range m.CreatePrivEvents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCreatePubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CreatePubEvents.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCreatePubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CreatePubEvents) > 0 {
		for _, e := range m.CreatePubEvents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetCreatePrivEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePrivEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePrivEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatePrivEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePrivEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePrivEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePrivEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreatePrivEvents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePrivEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePrivEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePrivEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePrivEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePrivEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePrivEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePrivEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatePrivEvents = append(m.CreatePrivEvents, CreatePrivEvents{})
			if err := m.CreatePrivEvents[len(m.CreatePrivEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatePubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreatePubEvents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatePubEvents = append(m.CreatePubEvents, CreatePubEvents{})
			if err := m.CreatePubEvents[len(m.CreatePubEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
